import re
from sqlalchemy import inspect, text, select
from app import DB, engine, Customer, CustomerSite

CUSTOMERS = [["AARMAN AUTOMATION",None,"D.NO 3/263/1,447/1C VEDASAMY KOVIL THOTTAM, MUTHUGOUNDENPUDUR,SULUR, COIMBATORE-641402, TAMIL NADU INDIA"],["ABEE TECHNICALS","33AAQFA0396M1Z3","S.F. NO.299, ELLAPPAN STREET, V.K. ROAD, THANNEERPANDHAL, PEELAMEDU, COIMBATORE - 641004."],["ABIPET TECHNOLOGIES PRIVATE LIMITED",None,"18, KR PURAM, AVARAMPALAYAM, RD, GANAPATHY (P.O), COIMBATORE - 641006"],["AMMA ALLOYS (INDIA) P LTD",None,"369/3, APPANAICKENPATTY PUDUR, PAPPAMPATTY(VIA), COIMBATORE, TAMILNADU 641402"],["AMPO VALVES INDIA PVT LTD",None,"SF.NO.27/2 & 28/3B, PONNANDAMPALAYAM, ARASUR, SULUR, COIMBATORE - 641659"],["ANDERSON GREENWOOD CROSBY SANMAR LIMITED","33AAACT7409H1ZH","88/1B, VADUGAPPTTI VILLAGE VIRALIMALAI, VIRALIMALAI, PUDUKOTTAI (DT) PIN-621316"],["ANNA INDUSTRIES",None,"SITE NO C, SHREE LAKSHMI INDUSTRIAL COMPLEX, SF NO 306/2 SENGODA GOUNDAN PUDUR, ARASUR, COIMBATORE - 641407"],["ANUGRAHA VALVE CASTINGS LIMITED - UNIT-II","33AACCA2285Q1ZF","S.F. NO 391/1, 394/1D,394/2, SENGODA GOUNDEN PUDUR, ARASUR VILLAGE, COIMBATORE - 641407"],["AQUA TECHNOLOGIES","33APUPG1245C1Z8","18B, RAJAJI NAGAR, SINGANALLUR, COIMBATORE - 641005"],["AQUASUB ENGINEERING UNIT - IV",None,"S.F.NO: 420 J.N.PALAYM, NEHRU COLONY, K. VADAMADURAI POST, COIMBATORE -641017"],["AQUASUB ENGINEERING UNIT - IV FOUNDERY - II",None,"NEHRU COLONY JN PALAYAM, K VADAMADURAI, COIMBATORE - 641017"],["ARUNA ALLOY STEELS PVT LIMITED - UNIT 3",None,"NO.1, MELUR ROAD, NARASINGAMPATTI, MADURAI - 625122"],["ASHITECH",None,"SF NO.278/1-B, NEAR ARIVOLI NAGAR, NO.5, BILICHI VILLAGE, COIMBATORE - 641019"],["AYYAPPA TOOLING ENGINEERS","33AUCPK1601P1ZT","73/2, KUNNINAICKER THOTTAM, ATHIPALAYAM ROAD, CHINNAVEDAMPATTI, COIMBATORE-641049"],["BARANI HYDRAULICS INDIA PRIVATE LIMITED","33AACCB4616L1ZT","SF NOS:507/1C1,1C2 ARASUR VILLAGE, SULUR TALUK, ARASUR, COIMBATORE -641407"],["BHARAT FRITZ WERNER LTD","33AAACB5723A1ZG","NO.7, KARAYAMPALAYAM ROAD MYLAMPATTI (PO), BEHIND HOTEL GOKULAM PARK, COIMBATORE-641062"],["CONCOCT TECHNOLOGIES",None,"S.F.NO 7/4, JAGANATHAN INDUSTRIAL ESTATE, CHINNAVEDAMPATTI, COIMBATORE-641049"],["CS INDUSTRIEES",None,"3C, ATHIPALAYAM PIRIYU OPP, MARIALLAYA CHRUCH, GANAPATHY, COIMBATORE - 641006"],["DYNAMIC ENGINEERING",None,"S.F.NO 9/3, SITE NO.14, L.G.B. NAGAR, 2ND STREET EXTN, SARAVAMPATTI (P.O), COIMBATORE - 641035"],["ELLEM ENGINEERING",None,"S.F.No.99/2A, 21/6, Sree Maruthi Industrial Estate, School Road, Chinnavedampatti, Coimbatore-641049"],["EPPINGER TOOLING ASIA PVT LTD",None,"S.F.NO.345/2A,2B, KONDAMPATTY, KINATHUKADAVU TALUK, COIMBATORE - 641202"],["EXCEL ENGINEERING",None,"129/1, BHARATHIPURAM EXTENSION, PALLAPALAYAM POST, IRUGUR VIA, COIMBATORE - 641033"],["GEEKEYY ENGINEERING CO.",None,"1/450-4, KANAVEDAN KOVIL ROAD, MUTHALIPALAYAM, ARASUR(P.O), COIMBATORE - 641407"],["GEM METAL INDUSTRIES",None,"566/1-D, THADAGAM ROAD, SOMAYAPALAYAM, KANUVAI POST, COIMBATORE-641108"],["GKR HI-TECH HEAVY ENGINEERING",None,"S.F.NO.106/4A-3, REVENUE NAGAR, SARAVANAMPATTI NORTH, COIMBATORE - 641035"],["GOUTHAM AANOORAA INC",None,"SF.NO.189/1, NARANAPURAM, ANNUR, CODISSIA INDUSTRIAL PARK, COIMBATORE - 641107"],["GTN ENGINEERING ( INDIA ) LTD - UNIT -1 ( PALM )",None,"S.F NO.94/3A DOOR NO.2/439 SEMMIPALAYAM VILLAGE, K.S.N. PURAM(PO), PALLADAM, TIRUPUR-641662"],["HARIHAR ALLOYS (P) LTD",None,"SF NO 80/61,80/62,80/68, VELLORE ROAD, ILLUPUR(TK), VIRALIMALAI, PUDUKKOTTAI - 621316"],["HAWLE VALVES INDIA PVT LTD",None,"483, KAMARAJ ROAD, SINGANALLUR, COIMBATORE - 641015"],["HI TECH INDUSTRIES",None,"SF NO.137/2B1A, OM SAKTHI NAGAR, CHINNAVEDAMPATTI, COIMBATORE-641049"],["HIGH PRECISION INDUSTRY",None,"UNIT-1 3/170, A-3, SIVASAKTHI COLONY, INDUSTRIAL ESTATE POST, COIMBATORE - 641021"],["HINDUSTAN AUTOMATIONS",None,"NO.1/450-3, KANAVEDAN KOVIL ROAD, MUTHALIPALAYAM, ARASUR POST, COIMBATORE - 641407"],["INTEGRA AUTOMATION PRIVATE LIMITED -UNIT-IV-A",None,"SF NO 238, KURUNALLI PALAYAM VILLAGE, KOTHAVAD VADACHITTUR VIA, COIMBATORE - 642120"],["JAD ENGINEERING INDUSTRIES",None,"10H, GANAPATHY GRAMAM, GANAPATHYPUTHUR, SATHI ROAD CROSS, OLD E.S.I ROAD, COIMBATORE-641006"],["JAYAKUMAR INDUSTRIES",None,"6-A, KONDASAMY NAGAR, B.R. PURAM, PEELAMEDU, COIMBATORE - 641004"],["JAYNBE INDUSTRIE",None,"SF NO.105, GKD SCHOOL BACKSIDE, PERIYANAICKENPALAYAM, COIMBATORE - 641020"],["JKS PRECISION ENGINEERING PRIVATE LIMITED",None,"SF.NO:173/1, 5/82 B1, VELLANAIPATTI, COIMBATORE - 641048"],["JS AUTO CAST FOUNDRY INDIA PRIVATE LIMITED",None,"165/1, Semba Gounden Pudur, Kuppepalayam, Coimbatore"],["JUSTIN INDUSTRIES",None,"SF NO:96/1C - 3/582, V.M.THOTTAM, K.VADAMADURAI, COIMBATORE - 641017"],["KARMAN INTERNATIONAL PVT LTD",None,"NO 70/2B, 12/1B, ATHIPALAYAM ROAD, CHINNAVEDAMPATTI, COIMBATORE - 641006"],["KSB LIMITED",None,"VALVES DIVISION, 151, MTP ROAD, NSN PALAYAM, COIMBATORE - 641031"],["KSV ENGINEERS",None,"6/12A BHARATHIPURAM, PALLAPALAYAM, COIMBATORE - 641103"],["KVR PRECISION INDUSTRIES",None,"SF.NO.338/2, SITE NO.103, GANDHI NAGAR, IRUGUR, COIMBATORE - 641103"],["LAKSHMI LIFE SCIENCES PRIVATE LIMITED",None,"UNIT-1, SF.NO.113/2, ANNUR ROAD, ARASUR VILLAGE, SULUR TALUK, COIMBATORE"],["LAKSHMI MACHINE CONTROLS",None,"NO.18, V.G. RAO NAGAR, PHASE II, GANAPATHY, COIMBATORE - 641006"],["LAKSHMI RING TRAVELLERS (COIMBATORE)PRIVATE LIMITED","33AAACL3736F1ZV","SULUR RAILWAY FEEDER ROAD, KURUMBALAYAM, COIMBATORE - 641402"],["MAHENDRA PUMPS (P) LTD",None,"733, PULIYAKULAM, COIMBATORE - 641045"],["MAHESH ENGINEERING INDUSTRIES",None,"SF NO.827/1, RAMASWAMY NAGAR, KARUPARAYAN PALAYAM VIA, CHINNIYAMPALAYAM POST, COIMBATORE - 641062"],["MAKINO INDIA PRIVATE LIMITED","33AACCM6536A1ZY","S.F.NO.477/2B, AVINASHI NH, KARUMATHAMPATTY VILLAGE, SULUR TALUK, COIMBATORE - 641659"],["MANTO CNC TECHNOLOGIES",None,"D.NO.5-126-A2, MOLAPALAYAM ROAD, VELLANAIPATTI VILLAGE, COIMBATORE - 641048"],["MATRIX ENGINEERING SOLUTIONS",None,"SF 645/4, VELLANAIPATTI, MOLAPALAYAM ROAD, COIMBATORE - 641048"],["MECHNO CRAFT ENGINEERING INDIA PVT MTD",None,"1/259-E, NEAR COSMAFAN FOUNDRY COMPLEX, PACHAPALAYAM VILLAGE, ARASUR, COIMBATORE - 641407"],["MOGLI LABS (INDIA) PRIVATE LIMITED",None,"NO.112 D, THANNEER PANDAL, VK ROAD, BR PURAM, PEELAMEDU, COIMBATORE - 641004"],["PAG INDUSTRIES",None,"SF.NO 34/1A & 2A, PURUSHOTHTHAMAN NAGAR, PEEDAMPALLI POST, COIMBATORE - 641016"],["PARTHASARATHY CNC TECHNOLOGY PVT LTD",None,"SF NO.188, B-1, DEVARAYAPURAM VILLAGE, POLLACHI-COIMBATORE MAIN ROAD, KINATHUKADAVU TALUK, COIMBATORE - 641110"],["PR CNC TECHNOLOGIES",None,"NO 4/271, SF NO 364/1 & 381/2A, SEERAPALAYAM VILLAGE, OTTAKKAL MANDAPAM ROAD, MADUKKARAI, COIMBATORE - 641105"],["PROCOS MECHATRONICS PRIVATE LIMITED",None,"NO 5/153/7, POOLAKKADU THOTAM, ARASUR, COIMBATORE - 641407"],["RAJVEER INDUSTRY",None,"PLOT NO.55, GAMANGATTI AREA, NEAR KSRTC TRAINING CENTRE, HUBLI - 580025"],["ROOTS INDUSTRIES INDIA PRIVATE LIMITED(HPED-UNIT-2)",None,"SF NO.414/2, 46/2-C AND 463/3, AGHARASAMAKULAM, ATHIPALAYAM, COIMBATORE-641110"],["S.V ENGINEERING",None,"SF.NO.217/1, EAST THOTTAM, SURYA NAGAR, ONDIPUDHUR, COIMBATORE-641016"],["SAKTHI FAB",None,"SF NO.277/2A3, NO.1 PERIYAKULAM ROAD, AMMAYANAICKANUR, NILAKOTTAI TALUK, DINDIGUL - 624201"],["SANMAR MATRIX METALS LIMITED",None,"NO 89/4A, VADUGAPATTI VILLAGE, ILLUPUR TK, VIRALIMALAI, PUDUKOTTAI DISTRICT"],["SBV ENGINEERING WORKS",None,"2/494-1, BETTATHAPURAM PUDUR, KARAMADAI POST, COIMBATORE - 641104"],["SMS GEARS",None,"A.N. NAGAR, VINAYAGAPURAM, V.K. ROAD, COIMBATORE - 641035"],["SNF COMPONENTS PRIVATE LIMITED",None,"D.NO.18/6, SF.NO.328/2A,329/2, THIRUSENTHURMURUGAN NAGAR, OPP. KUMARAN KOTTAM, SULUR, COIMBATORE - 641402"],["SREE SAKTHI ENGINEERING COMPANY",None,"858/1A1, BETTATHAPURAM STREET, KARAMADAI, COIMBATORE - 641104"],["SRI KRISHNA PATTERN ENGG. WORKS",None,"11/146-A, SIVASAKTHI COLONY, THEKKUPALAYAM POST, PERIYANAICKENPALAYAM, COIMBATORE - 641020"],["SRI SELVA VINAYAGA INDUSTRIES",None,"25, BALASUNDARAM LAYOUT, KRISHNAPURAM, SINGANALLUR, COIMBATORE-641005"],["SRI VISHNU FOUNDRIES",None,"OLD NO 1390A/NEW NO.234(B), SATHY ROAD, ERAN THOTTAM, GANAPATHY, COIMBATORE - 641006"],["TAK AUTOMATION",None,"36C-BLOCK A, PERIYA THOTTAM, KURUMPALAYAM ROAD, ATHAPPAKOUNDEN PUDUR, IRUGUR, COIMBATORE - 641103"],["USHA ENGINEERING WORKS",None,"S.F.NO.404, NARASIMHA NAICKEN PALAYAM, COIMBATORE - 641031"],["V.R.FOUNDRIES",None,"S.F.NO.478/1&2, PONNANDAMPALAYAM, KANIYUR VILLAGE, SULUR TALUK, COIMBATORE - 641659"],["VAF AERO SYSTEMS PRIVATE LIMITED",None,"SF.NO.162/2A, 12 EAST, CHENNAPACHETTY PUDUR POST, PADHUVAMPALLI VILLAGE, COIMBATORE"],["VAF Precision Engineering Private Limited",None,"SF NO.162/2A 12, East Chennappa Chetty Pudur Road, Poduvampalli Village, Coimbatore - 641659"],["VEEJEI AUTOMATION PRIVATE LIMITED",None,"NO.1/90A, KAREGOUNDANPLAYAM VILLAGE, ELLAPALAYAM(PO), POGALUR(VIA), COIMBATORE - 641697"],["VEEYES ALLOYS PRIVATE LIMITED","33AAACV6381N1ZX","S.F.489/5,490/1 &490/3, KONDAYAMPALAYAM ROAD, KEERANATHAM VILLAGE (PO), COIMBATORE - 641035"],["VELAN VALVES INDIA PVT LMT",None,"SF.NO.337/1, THENNAMPALAYAM-ANNUR ROAD, NARANAPURAM VILLAGE, COIMBATORE-641659"],["VPK PRECISION ENGINEERING",None,"4/89/D, SENTHAMPALAYAM, KURUMBAPALAYAM, MASAGOUNDEN CHETTIPALAYAM, COIMBATORE-641107"],["WARRIORS ENGINEERING",None,"4/95-2, PAARAIKOTTAI VILLAGE, INDUR POST, NALLAMPALLI TK, DHARMAPURI, TAMIL NADU - 636803"],["WHALE ENTERPRISE PRIVATE LIMITED",None,"NO.1/1D, VILANKURICHI ROAD, NEAR SENTHOTTAM, KALAPATTI, COIMBATORE - 641048"]]

ALIASES = {
    "JS AUTO CAST FOUNDRY INDIA PVT LTD UNIT 5": "JS AUTO CAST FOUNDRY INDIA PRIVATE LIMITED",
    "BARANI HYDRAULICS INDIA PRIVATE LIMITED UNIT II": "BARANI HYDRAULICS INDIA PRIVATE LIMITED",
    "VEEYES ALLOYS PRIVATE LIMITED PLANT 3": "VEEYES ALLOYS PRIVATE LIMITED",
    "VEEYES ALLOYS PVT LTD ASSEMBLY DIVISION": "VEEYES ALLOYS PRIVATE LIMITED",
}

def norm(value):
    s=(value or "").upper().replace("&"," AND ")
    s=re.sub(r"\bPVT\b"," PRIVATE ",s)
    s=re.sub(r"\bLTD\b"," LIMITED ",s)
    s=re.sub(r"[^A-Z0-9]+"," ",s)
    s=" ".join(s.split())
    return ALIASES.get(s,s)

def register(db):
    created=updated=merged=0
    incoming={norm(name):(name,gstin,address) for name,gstin,address in CUSTOMERS}
    existing=list(db.scalars(select(Customer).order_by(Customer.id)))
    by_key={}
    duplicates=[]
    for c in existing:
        key=norm(c.name)
        if key in by_key:
            duplicates.append((by_key[key],c))
        else:
            by_key[key]=c

    # Explicit legal-entity aliases that appeared in Tally as plant/unit variants.
    explicit_pairs=[
        ("JS AUTO CAST FOUNDRY INDIA PRIVATE LIMITED","JS AUTO CAST FOUNDRY INDIA PVT LTD UNIT - 5"),
        ("BARANI HYDRAULICS INDIA PRIVATE LIMITED","BARANI HYDRAULICS INDIA PRIVATE LIMITED - UNIT II"),
        ("VEEYES ALLOYS PRIVATE LIMITED","VEEYES ALLOYS PRIVATE LIMITED (PLANT-3)"),
        ("VEEYES ALLOYS PRIVATE LIMITED","VEEYES ALLOYS PVT LTD-  ASSEMBLY DIVISION"),
    ]
    refreshed=list(db.scalars(select(Customer).order_by(Customer.id)))
    exact={norm(c.name):c for c in refreshed}
    for a,b in explicit_pairs:
        ka,kb=norm(a),norm(b)
        ca,cb=exact.get(ka),exact.get(kb)
        if ca and cb and ca.id!=cb.id:
            keep,dup=(ca,cb) if ca.id<cb.id else (cb,ca)
            duplicates.append((keep,dup))

    seen=set()
    inspector=inspect(engine)
    fk_targets=[]
    for table in inspector.get_table_names():
        for fk in inspector.get_foreign_keys(table):
            if fk.get("referred_table")=="customers" and fk.get("referred_columns")==["id"]:
                cols=fk.get("constrained_columns") or []
                if len(cols)==1:
                    fk_targets.append((table,cols[0]))

    for keep,dup in duplicates:
        if dup.id in seen or keep.id==dup.id:
            continue
        for table,column in fk_targets:
            db.execute(text(f'UPDATE "{table}" SET "{column}"=:keep WHERE "{column}"=:dup'),{"keep":keep.id,"dup":dup.id})
        if not keep.gstin and dup.gstin: keep.gstin=dup.gstin
        if not keep.address and dup.address: keep.address=dup.address
        if not keep.phone and dup.phone: keep.phone=dup.phone
        if not keep.email and dup.email: keep.email=dup.email
        db.delete(dup); seen.add(dup.id); merged+=1
    db.flush()

    current=list(db.scalars(select(Customer).order_by(Customer.id)))
    by_key={norm(c.name):c for c in current}
    for key,(name,gstin,address) in incoming.items():
        c=by_key.get(key)
        if c:
            changed=False
            if gstin and c.gstin!=gstin: c.gstin=gstin; changed=True
            if address and (not c.address or len(address)>len(c.address)): c.address=address; changed=True
            if c.status!="Active": c.status="Active"; changed=True
            if changed: updated+=1
        else:
            c=Customer(name=name,gstin=gstin,address=address,status="Active")
            db.add(c); db.flush(); c.code=f"CUS-{c.id:04d}"
            by_key[key]=c; created+=1
    return {"created":created,"updated":updated,"duplicates_merged":merged,"total_import_rows":len(CUSTOMERS)}
